### ISSUE TITLE
cant run  P3d sketchs

### ISSUE THREAD

**Issue by zaki98D** [ruby-processing/propane#2]
Hi 
i have an issue when i try to run sketch that contain P3D
`
C:\Users\zaki\Desktop\ruby\Jruby>jruby P3.rb
Unhandled Java exception: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\zaki\Desktop\ruby\Jruby\natives\windows-amd64\\gluegen-rt.dll
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\zaki\Desktop\ruby\Jruby\natives\windows-amd64\\gluegen-rt.dll
                        loadLibrary at java/lang/ClassLoader:-1
                              load0 at java/lang/Runtime:-1
                               load at java/lang/System:-1
                loadLibraryInternal at com/jogamp/common/jvm/JNILibLoaderBase.java:624
                         access$000 at com/jogamp/common/jvm/JNILibLoaderBase.java:63
                        loadLibrary at com/jogamp/common/jvm/JNILibLoaderBase.java:106
                        loadLibrary at com/jogamp/common/jvm/JNILibLoaderBase.java:487
                        loadLibrary at com/jogamp/common/os/DynamicLibraryBundle.java:421
                                run at com/jogamp/common/os/Platform.java:317
                       doPrivileged at java/security/AccessController:-2
                           <clinit> at com/jogamp/common/os/Platform.java:287
                                run at com/jogamp/nativewindow/NativeWindowFactory.java:183
                       doPrivileged at java/security/AccessController:-2
                           <clinit> at com/jogamp/nativewindow/NativeWindowFactory.java:180
                                run at com/jogamp/newt/NewtFactory.java:68
                       doPrivileged at java/security/AccessController:-2
                           <clinit> at com/jogamp/newt/NewtFactory.java:65
                          initIcons at processing/opengl/PSurfaceJOGL.java:551
                          initFrame at processing/opengl/PSurfaceJOGL.java:137
                        initSurface at processing/core/PApplet.java:10451
                          runSketch at processing/core/PApplet.java:10338
                          runSketch at processing/core/PApplet.java:10516
                          runSketch at processing/core/PApplet.java:10522
                             invoke at java/lang/reflect/Method:-1
  invokeDirectWithExceptionHandling at org/jruby/javasupport/JavaMethod.java:438

                 tryProxyInvocation at org/jruby/javasupport/JavaMethod.java:623

                       invokeDirect at org/jruby/javasupport/JavaMethod.java:299

                         initialize at C:/jruby-9.1.6.0/lib/ruby/gems/shared/gems/propane-2.1.0-java/lib/propane/app.rb:116
                        newInstance at org/jruby/RubyClass.java:994
                               call at org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1
                  invokeOther11:new at P3.rb:17
                             <main> at P3.rb:17
                invokeWithArguments at java/lang/invoke/MethodHandle:-1
                          runScript at org/jruby/Ruby.java:846
                        runNormally at org/jruby/Ruby.java:761
                        runNormally at org/jruby/Ruby.java:779
                        runFromMain at org/jruby/Ruby.java:592
                      doRunFromMain at org/jruby/Main.java:425
                        internalRun at org/jruby/Main.java:313
                                run at org/jruby/Main.java:242
                               main at org/jruby/Main.java:204`
i am using windows8.1

jruby==> `C:\Users\zaki\Desktop\ruby\Jruby>jruby -v
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.11
1-b14 on 1.8.0_111-b14 +jit [mswin32-x86_64]`

java ==>`C:\Users\zaki\Desktop\ruby\Jruby>java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)`

propane ==>`C:\Users\zaki\Desktop\ruby\Jruby>propane -v
Propane version 2.1.0
JRuby version 9.1.6.0`
and thenk you :)

**Comment by monkstone** [comment]
This is to expected as I don't include the OPENGL binaries for windows see https://github.com/ruby-processing/propane/blob/master/pom.rb. Now you can fix this temporarily by copying the relevant binaries into the gem. However if you'd like to work with me (that is do the testing) I could produce a more permanent fix.

**Comment by zaki98D** [comment]
thank you for the help 
i am new to this but i will try to help  if you wanted anything

**Comment by zaki98D** [comment]
Ok i fixed it by putting these files in the sketch dirctory :D
[natives.zip](https://github.com/ruby-processing/propane/files/658501/natives.zip)

**Comment by monkstone** [comment]
@zaki98D

OK you should be able to do this
```bash
jgem install propane --pre
```

Which will install a custom version of propane with the 64 bit Windows binaries included. The simplest way to use the pre version is to uninstall release version first. To check:-

```bash
propane --version
# Propane version 2.2.0.pre
```

**Comment by monkstone** [comment]
See why this is an enhancement https://ruby-processing.github.io/propane/windows/ and not really a bug, but if you are really new to this then switching to linux might be a bit of a stretch.

**Comment by monkstone** [comment]
Nobody has taken the bait to try my Windows branch, well if the have the can't be arsed to report on it, so for the foreseeable future propane 3D is only for linux and MacOS
