### ISSUE TITLE
Installation instructions for sound/video library install

### ISSUE THREAD

**Issue by wcray** [ruby-processing/propane#27]
### Environment

OS X 10.11.5, though I expect this is universal

### Expected Behavior

Installation should install the libraries

### Actual Behavior

On a virgin system, installation does not install the libraries, because the installer script does not create the ~/.propane/Library/ directory, resulting in the cp -r erroring out.

### Other

either add

mkdir ~/.propane
mkdir ~/.propane/Libraries

after the propane installation instructions and before the samples/sound/video installation instructions, or, correct install scripts to create this directory hierarchy if missing

**Comment by monkstone** [comment]
Fixed for propane-2.7.2

**Comment by wcray** [comment]
On May 02, 2018, at 02:18 PM, Martin Prout <notifications@github.com> wrote:

@wcray thanks for report, I think this commit should fix problem 9b07093 it's certainly not 'dry' but I feel the need to delete library (in case obsolete version) before installing possibly new version otherwise directory would have been a good way to go. I'm interested on your experience with MacOS I'm a strictly linux man all feedback welcome.

Thanks Martin,

If there's any specific feedback/topics that you're interested in, I'm happy to provide what I can.  By trade I'm a cross between a Biophysicist and Computer Scientist, these days focusing primarily on complex data visualization in the biological sciences.  I've been doing this for a few years now (going on 30) so I have a few strong opinions on the subject :-)   I don't use Ruby or Processing enough to consider myself to be an expert in either, but Ruby is my go-to higher-level language of choice when I need to do something that's not a good fit for C, and I find Processing useful for quick visualization sketches when heavy lifting in OpenGL isn't necessary.

I've been away from Ruby-Processing for a while now, so your Propane implementation is a fresh go at this for me.

Best,
Will

**Comment by monkstone** [comment]
@wcray I guess you are not the ideal candidate for specific questions, I am happy if you find propane useful, please don't hesitate to report if something doesn't work as you think it should, or the documentation is not clear.  Going forward there may be issues with processing on MacOS, specifically because of proprietary (and probably obsoleted code) used by processing.org and this being withdrawn in jdk9-11, processing.org aren't going to do anything about it until October.  
PS my background was Biochemistry / Xenobiotic metabolism, but I'm retired so have time on my hands.

**Comment by wcray** [comment]
If there are specific things you're interested in testing, feel free to point me at them.  We have a vested interest in keeping processing as functional as possible on the Mac because, for various reasons, it's a lot easier to keep the lab running and the machines in front of the kiddies consistently configured and stable with MacOS than it is with Linux.   I'm not above making students go and run unit tests on stuff if it helps keep us working.

Best wishes,
Will



On May 04, 2018, at 02:04 PM, Martin Prout <notifications@github.com> wrote:

@wcray I guess you are not the ideal candidate for specific questions, I am happy if you find propane useful, please don't hesitate to report if something doesn't work as you think it should, or the documentation is not clear. Going forward there may be issues with processing on MacOS, specifically because of proprietary (and probably obsoleted code) used by processing.org and this being withdrawn in jdk9-11, processing.org aren't going to do anything about it until October.
PS my background was Biochemistry / Xenobiotic metabolism, but I'm retired so have time on my hands.
