### ISSUE TITLE
find_method doesnt exist

### ISSUE THREAD

**Issue by jtoy** [ruby-processing/propane#4]
According to the docs:
Because of this method madness, Propane::App has a convenience method for searching through them. find_method('ellipse') will return a list of the method names that may match what you’re looking for: ‘ellipse’, ‘ellipseMode’, and ‘ellipse_mode’.

 https://ruby-processing.github.io/propane/methods/processing_api

### Environment
propane (2.3.0 java)

jruby -v
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.102-b14 on 1.8.0_102-b14 +jit [darwin-x86_64]
uname -a
Darwin MacBook-Pro-6.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

### Expected Behavior
this method should work from irb
 Propane::App.find_method 'ellipse'  

it fails with: 
  Propane::App.find_method 'ellipse'
NoMethodError: undefined method `find_method' for Propane::App:Class
Did you mean?  define_method
	from org/jruby/RubyBasicObject.java:1653:in `method_missing'

### Actual Behavior
no method found

**Comment by monkstone** [comment]
This is advanced stuff and perhaps not well explained (especially for propane, perhaps you could help make it better). You actually need to create an instance to use `find_method`, and then you can use the global variable `$app`.
My advice is to create a sketch using `propane -c my_sketch 200 200`.
Fire up irb or pry (I use jpry command see below)

```bash
# in my .bashrc file
alias jpry="jruby -e \"require 'pry'; binding.pry\""
```

```ruby
load 'my_sketch.rb'

# at pry irb prompt
$app.find_method 'ellipse'
```
ellipse
ellipseMode
ellipse_mode
=> true
[3] pry(main)> $app.find_method('ellipse')
=> [:ellipse, :ellipseMode, :ellipse_mode]
[4] pry(main)>

**Comment by monkstone** [comment]
Even for JRubyArt the explanation of live coding is hidden the wiki. 
https://github.com/ruby-processing/JRubyArt/wiki/Live-Coding

**Comment by jtoy** [comment]
Great, I think getting the docs cleaned up a bit will be useful. ill look into it.
