### ISSUE TITLE
propane without xwindows?

### ISSUE THREAD

**Issue by jtoy** [ruby-processing/propane#5]
I use processing without a display all the time to create generative art. I usually make thousands of images and choose the ones I like.  I  use this guide: https://github.com/processing/processing/wiki/Running-without-a-Display
I tried doing the same thing with propane/jruby and no errors appear, but calling the save function does not actually save me any images. Can jruby save images under Xvfb or is there something special I need to do? Here is the test code I use:

``` require 'propane' 
class A < Propane::App
  def setup
    background(255,0,0)
    save "a.jpg"
    exit
  end
end
A.new
```

I use jruby 9.1.8.0, java version "1.8.0_121" and propane 2.3.0

**Comment by monkstone** [comment]
You might need a full qualified data path to save. Which is why I recommend using the `data_path` wrapper:-
```ruby
save(data_path('a.jpg'))
```
You could provide your own fully qualified path if you prefer.

**Comment by jtoy** [comment]
@monkstone that fixes it, that is so weird, the script works fine on a mac without paths, but on headless it doesn't work. Adding the path fixes it, thank you!  Maybe we should add this to the docs.

**Comment by monkstone** [comment]
@jtoy Yes please do other people might be interested. The path thing was bugbear for the original ruby-processing when running directly with jruby, but not when using java and jruby-complete (it meant anything like shader sketches only worked when using jruby-complete).

**Comment by monkstone** [comment]
This issue probably too subtle for most users, I have suggested using `data_path` in documentation, if problems are encountered.
